spring:
  application:
    name: resume-ats-task-runner

  datasource:
    url: jdbc:mysql://localhost:3306/resume_ats_task_runner
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true